/*
131_create_inspection_schema.sql — Create inspection schema
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'inspection')
BEGIN
    EXEC(N'CREATE SCHEMA inspection AUTHORIZATION dbo;');
END
GO
