/*
133_create_inspection_template_revision.sql — Create inspection.InspectionTemplate (revision)
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionTemplate', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionTemplate (
        InspectionTemplateId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionTemplate PRIMARY KEY CLUSTERED,
        InspectionTemplateFamilyId INT NOT NULL
            CONSTRAINT FK_InspectionTemplate_Family REFERENCES inspection.InspectionTemplateFamily(InspectionTemplateFamilyId),
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionTemplate_Plant REFERENCES dbo.Plant(PlantId),

        TemplateRevision INT NOT NULL,
        StatusCodeId INT NOT NULL
            CONSTRAINT FK_InspectionTemplate_StatusCode REFERENCES dbo.StatusCode(StatusCodeId),

        EffectiveFrom DATE NOT NULL,
        EffectiveTo DATE NULL,
        IsCurrentRevision BIT NOT NULL
            CONSTRAINT DF_InspectionTemplate_IsCurrentRevision DEFAULT 0,

        ChangeSummary NVARCHAR(500) NULL,
        DocumentId INT NULL
            CONSTRAINT FK_InspectionTemplate_Document REFERENCES dbo.Document(DocumentId),

        IsActive BIT NOT NULL
            CONSTRAINT DF_InspectionTemplate_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionTemplate_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplate_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplate_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT UQ_InspectionTemplate_Family_Revision UNIQUE (InspectionTemplateFamilyId, TemplateRevision),
        CONSTRAINT CK_InspectionTemplate_EffectiveDates CHECK (EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionTemplateHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionTemplate_Family_Current
        ON inspection.InspectionTemplate(InspectionTemplateFamilyId, IsCurrentRevision, StatusCodeId)
        INCLUDE (TemplateRevision, EffectiveFrom, EffectiveTo);

    CREATE INDEX IX_InspectionTemplate_PlantId_StatusCodeId
        ON inspection.InspectionTemplate(PlantId, StatusCodeId)
        INCLUDE (InspectionTemplateFamilyId, TemplateRevision, IsCurrentRevision, EffectiveFrom, EffectiveTo);
END
GO
