/*
135_create_inspection_template_field.sql — Create inspection.InspectionTemplateField
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionTemplateField', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionTemplateField (
        InspectionTemplateFieldId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionTemplateField PRIMARY KEY CLUSTERED,
        InspectionTemplateSectionId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateField_Section REFERENCES inspection.InspectionTemplateSection(InspectionTemplateSectionId),
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateField_Plant REFERENCES dbo.Plant(PlantId),

        FieldCode NVARCHAR(50) NOT NULL,
        FieldLabel NVARCHAR(200) NOT NULL,
        FieldTypeId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateField_FieldType REFERENCES dbo.LookupValue(LookupValueId),

        UnitOfMeasure NVARCHAR(30) NULL,
        DecimalPlaces TINYINT NULL,
        HelpText NVARCHAR(500) NULL,

        IsRequired BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateField_IsRequired DEFAULT 0,
        IsNcrRelevant BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateField_IsNcrRelevant DEFAULT 0,

        ControlPlanReferenceDocumentId INT NULL
            CONSTRAINT FK_InspectionTemplateField_ControlPlanDoc REFERENCES dbo.Document(DocumentId),
        StandardReferenceDocumentId INT NULL
            CONSTRAINT FK_InspectionTemplateField_StandardDoc REFERENCES dbo.Document(DocumentId),

        DefaultDefectTypeId INT NULL
            CONSTRAINT FK_InspectionTemplateField_DefaultDefectType REFERENCES dbo.DefectType(DefectTypeId),

        SortOrder INT NOT NULL
            CONSTRAINT DF_InspectionTemplateField_SortOrder DEFAULT 0,
        IsActive BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateField_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionTemplateField_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateField_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateField_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT UQ_InspectionTemplateField_Section_FieldCode UNIQUE (InspectionTemplateSectionId, FieldCode)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionTemplateFieldHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionTemplateField_SectionId_SortOrder
        ON inspection.InspectionTemplateField(InspectionTemplateSectionId, SortOrder)
        INCLUDE (FieldCode, FieldLabel, FieldTypeId, IsRequired, IsActive);

    CREATE INDEX IX_InspectionTemplateField_DefaultDefectTypeId
        ON inspection.InspectionTemplateField(DefaultDefectTypeId)
        INCLUDE (InspectionTemplateSectionId, FieldCode, FieldLabel)
        WHERE DefaultDefectTypeId IS NOT NULL;
END
GO
