/*
137_create_inspection_field_criteria.sql — Create inspection.InspectionTemplateFieldCriteria
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionTemplateFieldCriteria', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionTemplateFieldCriteria (
        InspectionTemplateFieldCriteriaId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionTemplateFieldCriteria PRIMARY KEY CLUSTERED,
        InspectionTemplateFieldId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateFieldCriteria_Field REFERENCES inspection.InspectionTemplateField(InspectionTemplateFieldId),
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateFieldCriteria_Plant REFERENCES dbo.Plant(PlantId),

        CriteriaTypeId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateFieldCriteria_CriteriaType REFERENCES dbo.LookupValue(LookupValueId),

        CriteriaName NVARCHAR(100) NULL,
        EvaluationOrder INT NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_EvaluationOrder DEFAULT 0,
        IsPrimary BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_IsPrimary DEFAULT 1,

        -- NCR trigger configuration (optional, opt-in)
        IsNcrAutoCreateEnabled BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_IsNcrAutoCreateEnabled DEFAULT 0,
        NcrTriggerTypeId INT NULL
            CONSTRAINT FK_InspectionTemplateFieldCriteria_NcrTriggerType REFERENCES dbo.LookupValue(LookupValueId),
        TriggerFailCount INT NULL,
        TriggerWindowMinutes INT NULL,
        RemeasureAllowedCount INT NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_RemeasureAllowedCount DEFAULT 0,

        DefectTypeId INT NULL
            CONSTRAINT FK_InspectionTemplateFieldCriteria_DefectType REFERENCES dbo.DefectType(DefectTypeId),

        IsActive BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateFieldCriteria_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT CK_InspectionTemplateFieldCriteria_RemeasureAllowedCount
            CHECK (RemeasureAllowedCount >= 0),
        CONSTRAINT CK_InspectionTemplateFieldCriteria_TriggerFailCount
            CHECK (TriggerFailCount IS NULL OR TriggerFailCount > 0),
        CONSTRAINT CK_InspectionTemplateFieldCriteria_TriggerWindowMinutes
            CHECK (TriggerWindowMinutes IS NULL OR TriggerWindowMinutes > 0)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionTemplateFieldCriteriaHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionTemplateFieldCriteria_FieldId_EvaluationOrder
        ON inspection.InspectionTemplateFieldCriteria(InspectionTemplateFieldId, EvaluationOrder)
        INCLUDE (CriteriaTypeId, IsPrimary, IsNcrAutoCreateEnabled, IsActive);
END
GO
