/*
143_create_inspection_assignment_rule.sql — Create inspection.InspectionTemplateAssignmentRule
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionTemplateAssignmentRule', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionTemplateAssignmentRule (
        InspectionTemplateAssignmentRuleId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionTemplateAssignmentRule PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Plant REFERENCES dbo.Plant(PlantId),
        InspectionTemplateFamilyId INT NOT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Family REFERENCES inspection.InspectionTemplateFamily(InspectionTemplateFamilyId),

        -- Wildcardable context (NULL = applies to all)
        CustomerId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Customer REFERENCES dbo.Customer(CustomerId),
        PartId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Part REFERENCES dbo.Part(PartId),
        LineTypeId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_LineType REFERENCES dbo.LineType(LineTypeId),
        ProductionLineId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_ProductionLine REFERENCES dbo.ProductionLine(ProductionLineId),
        LineStageId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_LineStage REFERENCES dbo.LineStage(LineStageId),
        EquipmentId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Equipment REFERENCES dbo.Equipment(EquipmentId),
        SupplierId INT NULL
            CONSTRAINT FK_InspectionTemplateAssignmentRule_Supplier REFERENCES dbo.Supplier(SupplierId),

        RulePriority INT NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_RulePriority DEFAULT 100,
        EffectiveFrom DATE NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_EffectiveFrom DEFAULT CONVERT(DATE, SYSUTCDATETIME()),
        EffectiveTo DATE NULL,
        IsActive BIT NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_IsActive DEFAULT 1,

        SpecificityScore AS (
              (CASE WHEN CustomerId       IS NULL THEN 0 ELSE 32 END)
            + (CASE WHEN PartId           IS NULL THEN 0 ELSE 32 END)
            + (CASE WHEN ProductionLineId IS NULL THEN 0 ELSE 16 END)
            + (CASE WHEN LineStageId      IS NULL THEN 0 ELSE  8 END)
            + (CASE WHEN EquipmentId      IS NULL THEN 0 ELSE  4 END)
            + (CASE WHEN SupplierId       IS NULL THEN 0 ELSE  2 END)
            + (CASE WHEN LineTypeId       IS NULL THEN 0 ELSE  1 END)
        ) PERSISTED,

        Notes NVARCHAR(500) NULL,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionTemplateAssignmentRule_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT CK_InspectionTemplateAssignmentRule_EffectiveDates CHECK (EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionTemplateAssignmentRuleHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionTemplateAssignmentRule_FamilyId_IsActive
        ON inspection.InspectionTemplateAssignmentRule(InspectionTemplateFamilyId, IsActive, EffectiveFrom, EffectiveTo)
        INCLUDE (RulePriority, SpecificityScore);

    CREATE INDEX IX_InspectionTemplateAssignmentRule_Match
        ON inspection.InspectionTemplateAssignmentRule(
            PlantId, CustomerId, PartId, LineTypeId, ProductionLineId, LineStageId, EquipmentId, SupplierId, IsActive
        )
        INCLUDE (InspectionTemplateFamilyId, RulePriority, SpecificityScore, EffectiveFrom, EffectiveTo);
END
GO
