/*
144_create_inspection_schedule_rule.sql — Create inspection.InspectionScheduleRule
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionScheduleRule', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionScheduleRule (
        InspectionScheduleRuleId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionScheduleRule PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionScheduleRule_Plant REFERENCES dbo.Plant(PlantId),
        InspectionTemplateAssignmentRuleId INT NOT NULL
            CONSTRAINT FK_InspectionScheduleRule_AssignmentRule REFERENCES inspection.InspectionTemplateAssignmentRule(InspectionTemplateAssignmentRuleId),

        FrequencyTypeId INT NOT NULL
            CONSTRAINT FK_InspectionScheduleRule_FrequencyType REFERENCES dbo.LookupValue(LookupValueId),

        IntervalMinutes INT NULL,
        RequiredPerShiftCount INT NULL,
        AnchorTypeId INT NULL
            CONSTRAINT FK_InspectionScheduleRule_AnchorType REFERENCES dbo.LookupValue(LookupValueId),

        DueGraceMinutes INT NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_DueGraceMinutes DEFAULT 0,
        MaxOverdueMinutes INT NULL,

        IsSkippable BIT NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_IsSkippable DEFAULT 0,

        StartTimeLocal TIME(0) NULL,
        EndTimeLocal TIME(0) NULL,

        IsActive BIT NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionScheduleRule_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT CK_InspectionScheduleRule_TimeWindow CHECK (
            (StartTimeLocal IS NULL AND EndTimeLocal IS NULL)
            OR (StartTimeLocal IS NOT NULL AND EndTimeLocal IS NOT NULL AND StartTimeLocal < EndTimeLocal)
        ),
        CONSTRAINT CK_InspectionScheduleRule_DueGraceMinutes CHECK (DueGraceMinutes >= 0),
        CONSTRAINT CK_InspectionScheduleRule_MaxOverdueMinutes CHECK (MaxOverdueMinutes IS NULL OR MaxOverdueMinutes > 0)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionScheduleRuleHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionScheduleRule_AssignmentRuleId_IsActive
        ON inspection.InspectionScheduleRule(InspectionTemplateAssignmentRuleId, IsActive)
        INCLUDE (FrequencyTypeId, IntervalMinutes, RequiredPerShiftCount, DueGraceMinutes, AnchorTypeId);
END
GO
