/*
145_create_production_run.sql — Create inspection.ProductionRun
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.ProductionRun', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.ProductionRun (
        ProductionRunId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_ProductionRun PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_ProductionRun_Plant REFERENCES dbo.Plant(PlantId),
        ProductionLineId INT NOT NULL
            CONSTRAINT FK_ProductionRun_ProductionLine REFERENCES dbo.ProductionLine(ProductionLineId),

        CustomerId INT NULL
            CONSTRAINT FK_ProductionRun_Customer REFERENCES dbo.Customer(CustomerId),
        PartId INT NULL
            CONSTRAINT FK_ProductionRun_Part REFERENCES dbo.Part(PartId),
        SupplierId INT NULL
            CONSTRAINT FK_ProductionRun_Supplier REFERENCES dbo.Supplier(SupplierId),

        WorkOrderNumber NVARCHAR(50) NULL,
        LotNumber NVARCHAR(50) NULL,

        StartedAtUtc DATETIME2(0) NOT NULL
            CONSTRAINT DF_ProductionRun_StartedAtUtc DEFAULT SYSUTCDATETIME(),
        EndedAtUtc DATETIME2(0) NULL,

        StartedById INT NOT NULL
            CONSTRAINT FK_ProductionRun_StartedBy REFERENCES dbo.AppUser(AppUserId),
        EndedById INT NULL
            CONSTRAINT FK_ProductionRun_EndedBy REFERENCES dbo.AppUser(AppUserId),

        StatusCodeId INT NOT NULL
            CONSTRAINT FK_ProductionRun_StatusCode REFERENCES dbo.StatusCode(StatusCodeId),

        Notes NVARCHAR(500) NULL,

        IsActive BIT NOT NULL
            CONSTRAINT DF_ProductionRun_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_ProductionRun_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_ProductionRun_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_ProductionRun_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT CK_ProductionRun_EndAfterStart CHECK (EndedAtUtc IS NULL OR EndedAtUtc >= StartedAtUtc)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.ProductionRunHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_ProductionRun_PlantId_LineId_StartedAtUtc
        ON inspection.ProductionRun(PlantId, ProductionLineId, StartedAtUtc DESC)
        INCLUDE (EndedAtUtc, CustomerId, PartId, WorkOrderNumber, LotNumber, StatusCodeId);

    CREATE INDEX IX_ProductionRun_Active
        ON inspection.ProductionRun(PlantId, ProductionLineId, EndedAtUtc)
        INCLUDE (ProductionRunId, StartedAtUtc, CustomerId, PartId, WorkOrderNumber)
        WHERE EndedAtUtc IS NULL;
END
GO
