/*
146_create_inspection_instance.sql — Create inspection.Inspection (instance header)
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.Inspection', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.Inspection (
        InspectionId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_Inspection PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_Inspection_Plant REFERENCES dbo.Plant(PlantId),

        ProductionRunId INT NULL
            CONSTRAINT FK_Inspection_ProductionRun REFERENCES inspection.ProductionRun(ProductionRunId),
        InspectionTemplateId INT NOT NULL
            CONSTRAINT FK_Inspection_Template REFERENCES inspection.InspectionTemplate(InspectionTemplateId),

        InspectionTemplateAssignmentRuleId INT NULL
            CONSTRAINT FK_Inspection_AssignmentRule REFERENCES inspection.InspectionTemplateAssignmentRule(InspectionTemplateAssignmentRuleId),
        InspectionScheduleRuleId INT NULL
            CONSTRAINT FK_Inspection_ScheduleRule REFERENCES inspection.InspectionScheduleRule(InspectionScheduleRuleId),

        StatusCodeId INT NOT NULL
            CONSTRAINT FK_Inspection_StatusCode REFERENCES dbo.StatusCode(StatusCodeId),

        OverallResultId INT NULL
            CONSTRAINT FK_Inspection_OverallResult REFERENCES dbo.LookupValue(LookupValueId),

        DueAtUtc DATETIME2(0) NULL,
        StartedAtUtc DATETIME2(0) NULL,
        SubmittedAtUtc DATETIME2(0) NULL,
        ReviewedAtUtc DATETIME2(0) NULL,
        ApprovedAtUtc DATETIME2(0) NULL,

        FilledById INT NULL
            CONSTRAINT FK_Inspection_FilledBy REFERENCES dbo.AppUser(AppUserId),
        SubmittedById INT NULL
            CONSTRAINT FK_Inspection_SubmittedBy REFERENCES dbo.AppUser(AppUserId),
        ReviewedById INT NULL
            CONSTRAINT FK_Inspection_ReviewedBy REFERENCES dbo.AppUser(AppUserId),
        ApprovedById INT NULL
            CONSTRAINT FK_Inspection_ApprovedBy REFERENCES dbo.AppUser(AppUserId),

        -- Context snapshot for audit + filtering
        CustomerId INT NULL
            CONSTRAINT FK_Inspection_Customer REFERENCES dbo.Customer(CustomerId),
        PartId INT NULL
            CONSTRAINT FK_Inspection_Part REFERENCES dbo.Part(PartId),
        SupplierId INT NULL
            CONSTRAINT FK_Inspection_Supplier REFERENCES dbo.Supplier(SupplierId),
        ProductionLineId INT NULL
            CONSTRAINT FK_Inspection_ProductionLine REFERENCES dbo.ProductionLine(ProductionLineId),
        LineStageId INT NULL
            CONSTRAINT FK_Inspection_LineStage REFERENCES dbo.LineStage(LineStageId),
        EquipmentId INT NULL
            CONSTRAINT FK_Inspection_Equipment REFERENCES dbo.Equipment(EquipmentId),

        ShiftId INT NULL
            CONSTRAINT FK_Inspection_Shift REFERENCES dbo.LookupValue(LookupValueId),

        WorkOrderNumber NVARCHAR(50) NULL,
        LotNumber NVARCHAR(50) NULL,

        IsAutoCreated BIT NOT NULL
            CONSTRAINT DF_Inspection_IsAutoCreated DEFAULT 0,

        AutoNcrId INT NULL
            CONSTRAINT FK_Inspection_AutoNcr REFERENCES quality.NonConformanceReport(NonConformanceReportId),

        VoidReason NVARCHAR(500) NULL,

        IsActive BIT NOT NULL
            CONSTRAINT DF_Inspection_IsActive DEFAULT 1,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_Inspection_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_Inspection_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_Inspection_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_Inspection_PlantId_DueAtUtc
        ON inspection.Inspection(PlantId, DueAtUtc)
        INCLUDE (StatusCodeId, InspectionTemplateId, ProductionLineId, PartId, CustomerId, IsAutoCreated);

    CREATE INDEX IX_Inspection_PlantId_LineId_SubmittedAtUtc
        ON inspection.Inspection(PlantId, ProductionLineId, SubmittedAtUtc DESC)
        INCLUDE (StatusCodeId, OverallResultId, PartId, CustomerId, InspectionTemplateId)
        WHERE SubmittedAtUtc IS NOT NULL;

    CREATE INDEX IX_Inspection_PlantId_PartId_SubmittedAtUtc
        ON inspection.Inspection(PlantId, PartId, SubmittedAtUtc DESC)
        INCLUDE (StatusCodeId, OverallResultId, ProductionLineId, CustomerId, InspectionTemplateId)
        WHERE SubmittedAtUtc IS NOT NULL;

    CREATE INDEX IX_Inspection_AutoNcrId
        ON inspection.Inspection(AutoNcrId)
        INCLUDE (InspectionId, PlantId, SubmittedAtUtc)
        WHERE AutoNcrId IS NOT NULL;
END
GO
