/*
147_create_inspection_finding.sql — Create inspection.InspectionFinding
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionFinding', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionFinding (
        InspectionFindingId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionFinding PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_Plant REFERENCES dbo.Plant(PlantId),

        InspectionId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_Inspection REFERENCES inspection.Inspection(InspectionId),

        InspectionTemplateFieldId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_Field REFERENCES inspection.InspectionTemplateField(InspectionTemplateFieldId),

        InspectionTemplateFieldCriteriaId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_Criteria REFERENCES inspection.InspectionTemplateFieldCriteria(InspectionTemplateFieldCriteriaId),

        ResultId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_Result REFERENCES dbo.LookupValue(LookupValueId),

        FindingTypeId INT NOT NULL
            CONSTRAINT FK_InspectionFinding_FindingType REFERENCES dbo.LookupValue(LookupValueId),

        DefectTypeId INT NULL
            CONSTRAINT FK_InspectionFinding_DefectType REFERENCES dbo.DefectType(DefectTypeId),

        FindingNotes NVARCHAR(500) NULL,

        NumericValue DECIMAL(18,4) NULL,
        Units NVARCHAR(30) NULL,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionFinding_CreatedDate DEFAULT SYSUTCDATETIME(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME2(0) NULL,

        ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
            CONSTRAINT DF_InspectionFinding_ValidFrom DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
            CONSTRAINT DF_InspectionFinding_ValidTo DEFAULT CONVERT(DATETIME2(0), '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),

        CONSTRAINT UQ_InspectionFinding_Inspection_Criteria UNIQUE (InspectionId, InspectionTemplateFieldCriteriaId)
    )
    WITH (SYSTEM_VERSIONING = ON (
        HISTORY_TABLE = audit.InspectionFindingHistory,
        HISTORY_RETENTION_PERIOD = 7 YEARS
    ));

    CREATE INDEX IX_InspectionFinding_InspectionId
        ON inspection.InspectionFinding(InspectionId)
        INCLUDE (InspectionTemplateFieldId, InspectionTemplateFieldCriteriaId, ResultId, FindingTypeId, DefectTypeId);

    CREATE INDEX IX_InspectionFinding_PlantId_DefectTypeId_CreatedDate
        ON inspection.InspectionFinding(PlantId, DefectTypeId, CreatedDate DESC)
        INCLUDE (InspectionId, ResultId, FindingTypeId)
        WHERE DefectTypeId IS NOT NULL;
END
GO
