/*
148_create_inspection_ncr_link.sql — Create inspection.InspectionNcrLink
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


IF OBJECT_ID(N'inspection.InspectionNcrLink', N'U') IS NULL
BEGIN
    CREATE TABLE inspection.InspectionNcrLink (
        InspectionNcrLinkId INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_InspectionNcrLink PRIMARY KEY CLUSTERED,
        PlantId INT NOT NULL
            CONSTRAINT FK_InspectionNcrLink_Plant REFERENCES dbo.Plant(PlantId),

        InspectionId INT NOT NULL
            CONSTRAINT FK_InspectionNcrLink_Inspection REFERENCES inspection.Inspection(InspectionId),
        NcrId INT NOT NULL
            CONSTRAINT FK_InspectionNcrLink_Ncr REFERENCES quality.NonConformanceReport(NonConformanceReportId),

        LinkReason NVARCHAR(200) NULL,

        CreatedBy INT NULL,
        CreatedDate DATETIME2(0) NOT NULL
            CONSTRAINT DF_InspectionNcrLink_CreatedDate DEFAULT SYSUTCDATETIME(),

        CONSTRAINT UQ_InspectionNcrLink_Inspection_Ncr UNIQUE (InspectionId, NcrId)
    );

    CREATE INDEX IX_InspectionNcrLink_NcrId
        ON inspection.InspectionNcrLink(NcrId)
        INCLUDE (InspectionId, PlantId, CreatedDate);
END
GO
