/*
155_add_rls_predicates_inspection.sql — Add inspection tables to security.PlantIsolationPolicy (RLS)
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO

DECLARE @PolicyName SYSNAME = N'PlantIsolationPolicy';
IF EXISTS (SELECT 1 FROM sys.security_policies WHERE name = @PolicyName AND SCHEMA_NAME(schema_id) = N'security')
BEGIN
    IF OBJECT_ID(N'inspection.InspectionTemplateFamily', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFamily')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateFamily;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFamily')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFamily AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFamily')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFamily AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplate', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplate')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplate;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplate')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplate AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplate')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplate AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplateSection', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateSection')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateSection;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateSection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateSection AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateSection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateSection AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplateField', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateField')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateField;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateField')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateField AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateField')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateField AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplateFieldOption', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldOption')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateFieldOption;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldOption')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFieldOption AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldOption')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFieldOption AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplateFieldCriteria', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldCriteria')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateFieldCriteria;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldCriteria')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFieldCriteria AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateFieldCriteria')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateFieldCriteria AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionCriteriaNumeric', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaNumeric')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionCriteriaNumeric;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaNumeric')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaNumeric AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaNumeric')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaNumeric AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionCriteriaAttribute', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAttribute')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionCriteriaAttribute;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAttribute')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaAttribute AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAttribute')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaAttribute AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionCriteriaSelection', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaSelection')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionCriteriaSelection;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaSelection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaSelection AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaSelection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaSelection AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionCriteriaAllowedOption', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAllowedOption')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionCriteriaAllowedOption;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAllowedOption')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaAllowedOption AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaAllowedOption')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaAllowedOption AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionCriteriaText', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaText')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionCriteriaText;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaText')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaText AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionCriteriaText')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionCriteriaText AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionTemplateAssignmentRule', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateAssignmentRule')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionTemplateAssignmentRule;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateAssignmentRule')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateAssignmentRule AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionTemplateAssignmentRule')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionTemplateAssignmentRule AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionScheduleRule', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionScheduleRule')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionScheduleRule;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionScheduleRule')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionScheduleRule AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionScheduleRule')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionScheduleRule AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.ProductionRun', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.ProductionRun')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.ProductionRun;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.ProductionRun')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.ProductionRun AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.ProductionRun')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.ProductionRun AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.Inspection', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.Inspection')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.Inspection;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.Inspection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.Inspection AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.Inspection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.Inspection AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionFinding', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionFinding')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionFinding;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionFinding')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionFinding AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionFinding')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionFinding AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionNcrLink', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionNcrLink')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionNcrLink;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionNcrLink')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionNcrLink AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionNcrLink')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionNcrLink AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseNumeric', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseNumeric')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseNumeric;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseNumeric')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseNumeric AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseNumeric')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseNumeric AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseAttribute', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttribute')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseAttribute;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttribute')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseAttribute AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttribute')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseAttribute AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseText', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseText')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseText;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseText')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseText AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseText')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseText AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseDateTime', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseDateTime')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseDateTime;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseDateTime')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseDateTime AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseDateTime')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseDateTime AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseSelection', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseSelection')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseSelection;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseSelection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseSelection AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseSelection')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseSelection AFTER UPDATE;');
        END
    END
    IF OBJECT_ID(N'inspection.InspectionResponseAttachment', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttachment')
              AND sp.predicate_type_desc = N'FILTER'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD FILTER PREDICATE security.fn_PlantAccessPredicate(PlantId)
                ON inspection.InspectionResponseAttachment;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttachment')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER INSERT'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseAttachment AFTER INSERT;');
        END
        IF NOT EXISTS (
            SELECT 1
            FROM sys.security_predicates sp
                INNER JOIN sys.security_policies pol ON sp.object_id = pol.object_id
            WHERE pol.name = @PolicyName
              AND SCHEMA_NAME(pol.schema_id) = N'security'
              AND sp.target_object_id = OBJECT_ID(N'inspection.InspectionResponseAttachment')
              AND sp.predicate_type_desc = N'BLOCK'
              AND sp.operation_desc = N'AFTER UPDATE'
        )
        BEGIN
            EXEC(N'ALTER SECURITY POLICY security.PlantIsolationPolicy
                ADD BLOCK PREDICATE security.fn_PlantWriteBlockPredicate(PlantId)
                ON inspection.InspectionResponseAttachment AFTER UPDATE;');
        END
    END
END
GO
