/*
156_seed_lookup_inspection.sql — Seed dbo.LookupCategory/LookupValue for Inspection module
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


-- Lookup Categories + Values for inspection module
-- Idempotent inserts using CategoryCode + ValueCode.

DECLARE @Categories TABLE (
    CategoryCode NVARCHAR(50) NOT NULL,
    CategoryName NVARCHAR(200) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsSystemManaged BIT NOT NULL
);

INSERT INTO @Categories(CategoryCode, CategoryName, Description, IsSystemManaged)
VALUES
(N'InspectionTemplateType',  N'Inspection Template Type', N'Template classification (Incoming/In-Process/Final/LPA/etc.)', 1),
(N'InspectionFieldType',     N'Inspection Field Type',    N'Field rendering and response storage type', 1),
(N'InspectionCriteriaType',  N'Inspection Criteria Type', N'Criteria evaluation type', 1),
(N'InspectionFrequencyType', N'Inspection Frequency Type',N'Scheduling frequency mode', 1),
(N'InspectionAnchorType',    N'Inspection Anchor Type',   N'Anchor used when computing due times', 1),
(N'InspectionEvaluationResult', N'Inspection Evaluation Result', N'PASS/FAIL/MARGINAL/NA', 1),
(N'InspectionFindingType',   N'Inspection Finding Type',  N'Failure vs marginal vs observation', 1),
(N'InspectionNcrTriggerType',N'Inspection NCR Trigger Type', N'Auto-NCR trigger mode', 1);

-- Create categories if missing
INSERT INTO dbo.LookupCategory(CategoryCode, CategoryName, Description, IsSystemManaged, IsActive)
SELECT c.CategoryCode, c.CategoryName, c.Description, c.IsSystemManaged, 1
FROM @Categories c
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.LookupCategory lc WHERE lc.CategoryCode = c.CategoryCode
);

-- Template Type values
DECLARE @TemplateTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionTemplateType');

IF @TemplateTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @TemplateTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'INCOMING',      N'Incoming Material',      N'Incoming material receiving inspection', 10),
        (N'FIRST_PIECE',   N'First Piece',            N'First piece / setup inspection', 20),
        (N'IN_PROCESS',    N'In-Process',             N'In-process production inspection', 30),
        (N'FINAL',         N'Final / End-of-Line',    N'Final inspection prior to release/shipping', 40),
        (N'LPA',           N'Layered Process Audit',  N'Layered process audit checklist', 50),
        (N'FIRST_ARTICLE', N'First Article / PPAP',   N'PPAP / first article inspection', 60),
        (N'OTHER',         N'Other',                  N'Other inspection template type', 90)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @TemplateTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Field Type values
DECLARE @FieldTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionFieldType');

IF @FieldTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @FieldTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'NUMERIC',           N'Numeric Measurement', N'Decimal numeric measurement with units', 10),
        (N'ATTRIBUTE',         N'Pass / Fail',         N'Binary attribute pass/fail', 20),
        (N'TEXT',              N'Text',                N'Free text entry', 30),
        (N'DATETIME',          N'Date / Time',         N'DateTime capture', 40),
        (N'SELECTION_SINGLE',  N'Single Select',       N'Choose one option from list', 50),
        (N'SELECTION_MULTI',   N'Multi Select',        N'Choose multiple options from list', 60),
        (N'PHOTO_ATTACHMENT',  N'Photo / Attachment',  N'Attachment upload (photo, document)', 70)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @FieldTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Criteria Type values
DECLARE @CriteriaTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionCriteriaType');

IF @CriteriaTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @CriteriaTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'NUMERIC',    N'Numeric Range/Tolerance', N'Min/Max/Nominal criteria evaluation', 10),
        (N'ATTRIBUTE',  N'Attribute Pass/Fail',     N'Binary attribute evaluation', 20),
        (N'SELECTION',  N'Selection',              N'Option selection evaluation', 30),
        (N'TEXT',       N'Text',                   N'Text rule evaluation', 40)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @CriteriaTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Frequency Type values
DECLARE @FrequencyTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionFrequencyType');

IF @FrequencyTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @FrequencyTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'INTERVAL_MINUTES', N'Interval (Minutes)', N'Required every N minutes during active production', 10),
        (N'PER_SHIFT',        N'Per Shift',          N'Required a number of times per shift', 20),
        (N'PER_LOT',          N'Per Lot',            N'Required per lot or batch', 30),
        (N'PER_RUN_START',    N'Run Start',          N'Required at start of production run', 40),
        (N'AD_HOC',           N'Ad Hoc',             N'No schedule; manual creation only', 90)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @FrequencyTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Anchor Type values
DECLARE @AnchorTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionAnchorType');

IF @AnchorTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @AnchorTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'RUN_START',   N'Run Start',   N'Anchor from ProductionRun.StartedAtUtc', 10),
        (N'SHIFT_START', N'Shift Start', N'Anchor from shift start time', 20),
        (N'DAY_START',   N'Day Start',   N'Anchor from local day start', 30)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @AnchorTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Evaluation Result values
DECLARE @EvalResultCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionEvaluationResult');

IF @EvalResultCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @EvalResultCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'PASS',     N'Pass',     N'Meets criteria', 10),
        (N'FAIL',     N'Fail',     N'Does not meet criteria', 20),
        (N'MARGINAL', N'Marginal', N'In warning band or minor deviation', 30),
        (N'NA',       N'N/A',      N'Not applicable', 90)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @EvalResultCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- Finding Type values
DECLARE @FindingTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionFindingType');

IF @FindingTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @FindingTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'FAILURE',     N'Failure',     N'Criteria failed', 10),
        (N'MARGINAL',    N'Marginal',    N'Warning / marginal condition', 20),
        (N'OBSERVATION', N'Observation', N'Informational note', 30)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @FindingTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

-- NCR Trigger Type values
DECLARE @NcrTriggerTypeCategoryId INT = (SELECT LookupCategoryId FROM dbo.LookupCategory WHERE CategoryCode = N'InspectionNcrTriggerType');

IF @NcrTriggerTypeCategoryId IS NOT NULL
BEGIN
    INSERT INTO dbo.LookupValue(LookupCategoryId, ValueCode, ValueName, Description, SortOrder, IsActive)
    SELECT @NcrTriggerTypeCategoryId, v.ValueCode, v.ValueName, v.Description, v.SortOrder, 1
    FROM (VALUES
        (N'IMMEDIATE',        N'Immediate',        N'Create NCR on first qualifying failure', 10),
        (N'FAIL_COUNT_WINDOW',N'Threshold in Window', N'Create NCR when fail count threshold met within window', 20)
    ) v(ValueCode, ValueName, Description, SortOrder)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LookupValue lv
        WHERE lv.LookupCategoryId = @NcrTriggerTypeCategoryId AND lv.ValueCode = v.ValueCode
    );
END

GO
