/*
157_seed_document_types_inspection.sql — Seed dbo.DocumentType for inspection templates + attachments
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


-- Document types for inspection module
-- Idempotent inserts by TypeCode.

IF NOT EXISTS (SELECT 1 FROM dbo.DocumentType WHERE TypeCode = N'INSP_TEMPLATE')
BEGIN
    INSERT INTO dbo.DocumentType(TypeCode, TypeName, IsActive)
    VALUES (N'INSP_TEMPLATE', N'Inspection Form Template', 1);
END

IF NOT EXISTS (SELECT 1 FROM dbo.DocumentType WHERE TypeCode = N'INSP_ATTACHMENT')
BEGIN
    INSERT INTO dbo.DocumentType(TypeCode, TypeName, IsActive)
    VALUES (N'INSP_ATTACHMENT', N'Inspection Attachment', 1);
END
GO
