/*
158_seed_status_codes_inspection.sql — Seed dbo.StatusCode values required for Inspection module
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


/*
This migration seeds the StatusCode rows used by the Inspection module.

Because dbo.StatusCode DDL was not included in CODEBASE_REFERENCE.md, this script uses
dynamic schema discovery to locate the likely Code/Name/IsActive columns.

If dbo.StatusCode contains additional NOT NULL columns without defaults, this script will THROW
with an actionable message so the migration can be adjusted once the real schema is confirmed.
*/

IF OBJECT_ID(N'dbo.StatusCode', N'U') IS NULL
BEGIN
    PRINT N'dbo.StatusCode not found. Skipping inspection status seed.';
    RETURN;
END
GO

DECLARE @CodeCol SYSNAME = NULL;
DECLARE @NameCol SYSNAME = NULL;
DECLARE @IsActiveCol SYSNAME = NULL;
DECLARE @DescCol SYSNAME = NULL;
DECLARE @SortCol SYSNAME = NULL;

SELECT TOP (1) @CodeCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'StatusCode', N'StatusCodeCode', N'Code', N'Status', N'StatusValue');

SELECT TOP (1) @NameCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'StatusName', N'StatusCodeName', N'Name', N'DisplayName');

SELECT TOP (1) @IsActiveCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'IsActive', N'IsEnabled');

SELECT TOP (1) @DescCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'Description', N'Desc');

SELECT TOP (1) @SortCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'SortOrder', N'DisplayOrder', N'Order');

IF @CodeCol IS NULL OR @NameCol IS NULL
BEGIN
    THROW 53000, 'dbo.StatusCode schema not recognized (missing Code/Name column). Update 158_seed_status_codes_inspection.sql to match actual schema.', 1;
END

-- Validate there are no extra required columns without defaults that would block inserts.
IF EXISTS (
    SELECT 1
    FROM sys.columns c
    LEFT JOIN sys.default_constraints dc ON c.default_object_id = dc.object_id
    WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
      AND c.is_identity = 0
      AND c.is_computed = 0
      AND c.is_nullable = 0
      AND dc.object_id IS NULL
      AND c.name NOT IN (@CodeCol, @NameCol, ISNULL(@IsActiveCol, N''), ISNULL(@DescCol, N''), ISNULL(@SortCol, N''))
)
BEGIN
    DECLARE @MissingCols NVARCHAR(MAX) =
        STUFF((
            SELECT N', ' + c.name
            FROM sys.columns c
            LEFT JOIN sys.default_constraints dc ON c.default_object_id = dc.object_id
            WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
              AND c.is_identity = 0
              AND c.is_computed = 0
              AND c.is_nullable = 0
              AND dc.object_id IS NULL
              AND c.name NOT IN (@CodeCol, @NameCol, ISNULL(@IsActiveCol, N''), ISNULL(@DescCol, N''), ISNULL(@SortCol, N''))
            FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 2, '');

    THROW 53000, CONCAT('dbo.StatusCode has required columns without defaults (', @MissingCols, '). Add them to the insert list in 158_seed_status_codes_inspection.sql.'), 1;
END

DECLARE @InsertCols NVARCHAR(MAX) = QUOTENAME(@CodeCol) + N', ' + QUOTENAME(@NameCol);
DECLARE @InsertVals NVARCHAR(MAX) = N'@Code, @Name';

IF @IsActiveCol IS NOT NULL
BEGIN
    SET @InsertCols += N', ' + QUOTENAME(@IsActiveCol);
    SET @InsertVals += N', 1';
END

IF @DescCol IS NOT NULL
BEGIN
    SET @InsertCols += N', ' + QUOTENAME(@DescCol);
    SET @InsertVals += N', @Desc';
END

IF @SortCol IS NOT NULL
BEGIN
    SET @InsertCols += N', ' + QUOTENAME(@SortCol);
    SET @InsertVals += N', @Sort';
END

DECLARE @UpsertSql NVARCHAR(MAX) = N'
IF NOT EXISTS (SELECT 1 FROM dbo.StatusCode WHERE ' + QUOTENAME(@CodeCol) + N' = @Code)
BEGIN
    INSERT INTO dbo.StatusCode(' + @InsertCols + N') VALUES (' + @InsertVals + N');
END
';

DECLARE @Statuses TABLE (Code NVARCHAR(50), Name NVARCHAR(200), [Desc] NVARCHAR(500), Sort INT);
INSERT INTO @Statuses(Code, Name, [Desc], Sort)
VALUES
(N'INSP_TEMPLATE_DRAFT',   N'Inspection Template - Draft',      N'Draft controlled form template revision', 10),
(N'INSP_TEMPLATE_ACTIVE',  N'Inspection Template - Active',     N'Published and active template revision', 20),
(N'INSP_TEMPLATE_RETIRED', N'Inspection Template - Retired',    N'Retired template revision (no new use)', 30),

(N'INSP_DRAFT',        N'Inspection - Draft',          N'Inspection instance draft (not submitted)', 10),
(N'INSP_IN_PROGRESS',  N'Inspection - In Progress',    N'Inspection being filled', 20),
(N'INSP_SUBMITTED',    N'Inspection - Submitted',      N'Inspection submitted for review', 30),
(N'INSP_APPROVED',     N'Inspection - Approved',       N'Inspection approved/accepted', 40),
(N'INSP_REJECTED',     N'Inspection - Rejected',       N'Inspection rejected; rework required', 50),
(N'INSP_VOIDED',       N'Inspection - Voided',         N'Inspection voided/cancelled', 90),

(N'INSP_RUN_ACTIVE',   N'Production Run - Active',     N'Production run active (manual v1)', 10),
(N'INSP_RUN_ENDED',    N'Production Run - Ended',      N'Production run ended', 20);

DECLARE @Code NVARCHAR(50), @Name NVARCHAR(200), @Desc NVARCHAR(500), @Sort INT;

DECLARE cur CURSOR LOCAL FAST_FORWARD FOR
    SELECT Code, Name, [Desc], Sort FROM @Statuses ORDER BY Sort;

OPEN cur;
FETCH NEXT FROM cur INTO @Code, @Name, @Desc, @Sort;

WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC sys.sp_executesql
        @UpsertSql,
        N'@Code NVARCHAR(50), @Name NVARCHAR(200), @Desc NVARCHAR(500), @Sort INT',
        @Code = @Code, @Name = @Name, @Desc = @Desc, @Sort = @Sort;

    FETCH NEXT FROM cur INTO @Code, @Name, @Desc, @Sort;
END

CLOSE cur;
DEALLOCATE cur;
GO
