/*
159_workflow_allow_entity_types_inspection.sql — Extend workflow.WorkflowProcess.EntityType constraint for Inspection module
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


/*
The workflow engine restricts WorkflowProcess.EntityType via a CHECK constraint.
To add new workflow-managed entities, we must extend the allowed values.

Adds:
- InspectionTemplate
- Inspection
*/

IF OBJECT_ID(N'workflow.WorkflowProcess', N'U') IS NULL
BEGIN
    PRINT N'workflow.WorkflowProcess not found. Skipping workflow entity type constraint update.';
    RETURN;
END
GO

IF EXISTS (
    SELECT 1
    FROM sys.check_constraints cc
    WHERE cc.parent_object_id = OBJECT_ID(N'workflow.WorkflowProcess')
      AND cc.name = N'CK_WorkflowProcess_EntityType'
)
BEGIN
    DECLARE @Def NVARCHAR(MAX) =
        (SELECT cc.definition
         FROM sys.check_constraints cc
         WHERE cc.parent_object_id = OBJECT_ID(N'workflow.WorkflowProcess')
           AND cc.name = N'CK_WorkflowProcess_EntityType');

    IF (@Def NOT LIKE N'%InspectionTemplate%' OR @Def NOT LIKE N'%Inspection%')
    BEGIN
        ALTER TABLE workflow.WorkflowProcess DROP CONSTRAINT CK_WorkflowProcess_EntityType;

        ALTER TABLE workflow.WorkflowProcess WITH CHECK
        ADD CONSTRAINT CK_WorkflowProcess_EntityType CHECK (
            EntityType IN (
                N'NCR',
                N'CAPA',
                N'CustomerComplaint',
                N'SupplierCAR',
                N'AuditFinding',
                N'EightDReport',
                N'InspectionTemplate',
                N'Inspection'
            )
        );
    END
END
GO
