/*
160_seed_workflow_inspection.sql — Seed workflow processes/states/transitions for Inspection module
Generated by: Quality Inspection Forms Module package
Notes:
- Idempotent (existence-guarded) migration
- Uses system-versioned temporal tables for auditable entities
*/
SET NOCOUNT ON;
GO


/*
Seeds workflow definitions for:
- EntityType = 'InspectionTemplate'
- EntityType = 'Inspection'

Depends on:
- 158_seed_status_codes_inspection.sql (StatusCode rows exist)
- 159_workflow_allow_entity_types_inspection.sql (EntityType constraint updated)

Approval chains are NOT hard-seeded here because RoleId values are environment-specific.
*/

IF OBJECT_ID(N'workflow.WorkflowProcess', N'U') IS NULL
BEGIN
    PRINT N'workflow.WorkflowProcess not found. Skipping workflow seed.';
    RETURN;
END

IF OBJECT_ID(N'dbo.StatusCode', N'U') IS NULL
BEGIN
    THROW 53000, 'dbo.StatusCode not found. Cannot seed inspection workflow.', 1;
END
GO

-- Discover code column for dbo.StatusCode (for lookups by code).
DECLARE @CodeCol SYSNAME = NULL;
SELECT TOP (1) @CodeCol = c.name
FROM sys.columns c
WHERE c.object_id = OBJECT_ID(N'dbo.StatusCode')
  AND c.name IN (N'StatusCode', N'StatusCodeCode', N'Code', N'Status', N'StatusValue');

IF @CodeCol IS NULL
BEGIN
    THROW 53000, 'dbo.StatusCode schema not recognized (missing code column). Cannot seed inspection workflow.', 1;
END

DECLARE @GetStatusIdSql NVARCHAR(MAX) =
    N'SELECT @StatusCodeId = StatusCodeId FROM dbo.StatusCode WHERE ' + QUOTENAME(@CodeCol) + N' = @Code;';

DECLARE @StatusTemplateDraft INT, @StatusTemplateActive INT, @StatusTemplateRetired INT;
DECLARE @StatusInspDraft INT, @StatusInspInProgress INT, @StatusInspSubmitted INT, @StatusInspApproved INT, @StatusInspRejected INT, @StatusInspVoided INT;

EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_TEMPLATE_DRAFT',   @StatusCodeId=@StatusTemplateDraft OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_TEMPLATE_ACTIVE',  @StatusCodeId=@StatusTemplateActive OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_TEMPLATE_RETIRED', @StatusCodeId=@StatusTemplateRetired OUTPUT;

EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_DRAFT',       @StatusCodeId=@StatusInspDraft OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_IN_PROGRESS', @StatusCodeId=@StatusInspInProgress OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_SUBMITTED',   @StatusCodeId=@StatusInspSubmitted OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_APPROVED',    @StatusCodeId=@StatusInspApproved OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_REJECTED',    @StatusCodeId=@StatusInspRejected OUTPUT;
EXEC sys.sp_executesql @GetStatusIdSql, N'@Code NVARCHAR(50), @StatusCodeId INT OUTPUT', @Code=N'INSP_VOIDED',      @StatusCodeId=@StatusInspVoided OUTPUT;

IF @StatusTemplateDraft IS NULL OR @StatusTemplateActive IS NULL OR @StatusTemplateRetired IS NULL
BEGIN
    THROW 53000, 'InspectionTemplate status codes not found. Ensure 158_seed_status_codes_inspection.sql ran successfully.', 1;
END

IF @StatusInspDraft IS NULL OR @StatusInspInProgress IS NULL OR @StatusInspSubmitted IS NULL OR @StatusInspApproved IS NULL OR @StatusInspRejected IS NULL OR @StatusInspVoided IS NULL
BEGIN
    THROW 53000, 'Inspection status codes not found. Ensure 158_seed_status_codes_inspection.sql ran successfully.', 1;
END

-- Create workflow processes
IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowProcess WHERE EntityType = N'InspectionTemplate')
BEGIN
    INSERT INTO workflow.WorkflowProcess(EntityType, ProcessName, ProcessVersion, IsActive)
    VALUES (N'InspectionTemplate', N'Inspection Template Workflow', N'1.0', 1);
END

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowProcess WHERE EntityType = N'Inspection')
BEGIN
    INSERT INTO workflow.WorkflowProcess(EntityType, ProcessName, ProcessVersion, IsActive)
    VALUES (N'Inspection', N'Inspection Workflow', N'1.0', 1);
END

DECLARE @ProcessTemplateId INT = (SELECT WorkflowProcessId FROM workflow.WorkflowProcess WHERE EntityType = N'InspectionTemplate');
DECLARE @ProcessInspectionId INT = (SELECT WorkflowProcessId FROM workflow.WorkflowProcess WHERE EntityType = N'Inspection');

-- Create workflow states (InspectionTemplate)
DECLARE @StateTemplateDraftId INT, @StateTemplateActiveId INT, @StateTemplateRetiredId INT;

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateDraft)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessTemplateId, @StatusTemplateDraft, N'Start', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateActive)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessTemplateId, @StatusTemplateActive, N'Normal', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateRetired)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessTemplateId, @StatusTemplateRetired, N'Terminal', 1);

SELECT @StateTemplateDraftId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateDraft;
SELECT @StateTemplateActiveId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateActive;
SELECT @StateTemplateRetiredId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessTemplateId AND StatusCodeId = @StatusTemplateRetired;

-- Create workflow states (Inspection)
DECLARE @StateInspDraftId INT, @StateInspInProgressId INT, @StateInspSubmittedId INT, @StateInspApprovedId INT, @StateInspRejectedId INT, @StateInspVoidedId INT;

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspDraft)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspDraft, N'Start', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspInProgress)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspInProgress, N'Normal', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspSubmitted)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspSubmitted, N'Normal', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspApproved)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspApproved, N'Terminal', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspRejected)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspRejected, N'Normal', 1);

IF NOT EXISTS (SELECT 1 FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspVoided)
    INSERT INTO workflow.WorkflowState(WorkflowProcessId, StatusCodeId, StateType, IsActive) VALUES (@ProcessInspectionId, @StatusInspVoided, N'Cancelled', 1);

SELECT @StateInspDraftId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspDraft;
SELECT @StateInspInProgressId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspInProgress;
SELECT @StateInspSubmittedId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspSubmitted;
SELECT @StateInspApprovedId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspApproved;
SELECT @StateInspRejectedId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspRejected;
SELECT @StateInspVoidedId = WorkflowStateId FROM workflow.WorkflowState WHERE WorkflowProcessId = @ProcessInspectionId AND StatusCodeId = @StatusInspVoided;

-- Seed transitions (InspectionTemplate)
IF NOT EXISTS (
    SELECT 1 FROM workflow.WorkflowTransition
    WHERE WorkflowProcessId = @ProcessTemplateId AND FromStateId = @StateTemplateDraftId AND ToStateId = @StateTemplateActiveId
)
BEGIN
    INSERT INTO workflow.WorkflowTransition(WorkflowProcessId, FromStateId, ToStateId, TransitionName, GuardType, GuardExpression, RequiredRoleId, SlaHours, SlaBaselineType, IsAutoFire, IsActive)
    VALUES (@ProcessTemplateId, @StateTemplateDraftId, @StateTemplateActiveId, N'Publish', NULL, NULL, NULL, NULL, NULL, 0, 1);
END

IF NOT EXISTS (
    SELECT 1 FROM workflow.WorkflowTransition
    WHERE WorkflowProcessId = @ProcessTemplateId AND FromStateId = @StateTemplateActiveId AND ToStateId = @StateTemplateRetiredId
)
BEGIN
    INSERT INTO workflow.WorkflowTransition(WorkflowProcessId, FromStateId, ToStateId, TransitionName, GuardType, GuardExpression, RequiredRoleId, SlaHours, SlaBaselineType, IsAutoFire, IsActive)
    VALUES (@ProcessTemplateId, @StateTemplateActiveId, @StateTemplateRetiredId, N'Retire', NULL, NULL, NULL, NULL, NULL, 0, 1);
END

-- Seed transitions (Inspection)
DECLARE @Transitions TABLE (FromId INT, ToId INT, Name NVARCHAR(100));
INSERT INTO @Transitions(FromId, ToId, Name)
VALUES
(@StateInspDraftId,      @StateInspInProgressId, N'Start'),
(@StateInspInProgressId, @StateInspSubmittedId,   N'Submit'),
(@StateInspSubmittedId,  @StateInspApprovedId,    N'Approve'),
(@StateInspSubmittedId,  @StateInspRejectedId,    N'Reject'),
(@StateInspRejectedId,   @StateInspInProgressId,  N'Rework'),
(@StateInspDraftId,      @StateInspVoidedId,      N'Void'),
(@StateInspInProgressId, @StateInspVoidedId,      N'Void'),
(@StateInspRejectedId,   @StateInspVoidedId,      N'Void');

DECLARE @FromId INT, @ToId INT, @TName NVARCHAR(100);

DECLARE tcur CURSOR LOCAL FAST_FORWARD FOR SELECT FromId, ToId, Name FROM @Transitions;
OPEN tcur;
FETCH NEXT FROM tcur INTO @FromId, @ToId, @TName;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM workflow.WorkflowTransition
        WHERE WorkflowProcessId = @ProcessInspectionId AND FromStateId = @FromId AND ToStateId = @ToId AND TransitionName = @TName
    )
    BEGIN
        INSERT INTO workflow.WorkflowTransition(WorkflowProcessId, FromStateId, ToStateId, TransitionName, GuardType, GuardExpression, RequiredRoleId, SlaHours, SlaBaselineType, IsAutoFire, IsActive)
        VALUES (@ProcessInspectionId, @FromId, @ToId, @TName, NULL, NULL, NULL, NULL, NULL, 0, 1);
    END

    FETCH NEXT FROM tcur INTO @FromId, @ToId, @TName;
END

CLOSE tcur;
DEALLOCATE tcur;

GO
